"""Plot + README writers for the MCMC posterior-warming pipeline.

Notebook-side helpers are re-imported here; lifting them into
``ecosystem_complexity.visualize`` is Session F step 1.
"""
from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from ecosystem_complexity import mcmc as _mcmc

# NOTE: `src` importing from `notebooks` is a Session F step-1 target.
# For this PR the shim is preserved so the pipeline still runs.
from notebooks.paper_figs.utils import finalize_figure  # noqa: E402


def _supplementary_null_figure(
    null_samples: pd.DataFrame,
    null_summary: pd.DataFrame,
    output_dir: str,
) -> None:
    summary = null_summary.iloc[0]
    fig, ax = plt.subplots(figsize=(7.5, 5.0))
    ax.hist(null_samples["pearson_r"], bins=30, color="#C8D6D1", edgecolor="white")
    ax.axvline(float(summary["observed_pearson_r"]), color="#8C2F39", linewidth=2.0, label="Observed median-site r")
    ax.set_xlabel("Null Pearson r")
    ax.set_ylabel("Count")
    ax.set_title("Structural null from site priors")
    ax.text(
        0.02,
        0.98,
        (
            f"Observed percentile = {summary['observed_percentile']:.1f}\n"
            f"Empirical p = {summary['empirical_p_two_sided']:.3f}\n"
            f"Null median = {summary['null_pearson_r_median']:.2f}\n"
            f"Null 95% = [{summary['null_pearson_r_q025']:.2f}, {summary['null_pearson_r_q975']:.2f}]"
        ),
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=9,
        bbox={"facecolor": "white", "edgecolor": "0.85", "boxstyle": "round,pad=0.3"},
    )
    ax.legend(loc="upper right", fontsize=9)
    fig.tight_layout()
    alt_text = (
        "Histogram of the structural-null Pearson correlation distribution derived from independent prior draws at each site, "
        "propagated through the existing 100-year plus-4-degree-C warming experiment. A vertical line marks the observed "
        "cross-site correlation based on posterior median turnover separation and posterior median old-fraction response."
    )
    caption = (
        "Structural-null test for the turnover-separation versus old-fraction relationship. The null distribution was generated by "
        "drawing independent parameter vectors from each site's saved OE prior over the optimized state vector and propagating those "
        "draws through the existing standardized warming experiment. The observed cross-site Pearson correlation among posterior "
        "median site metrics lies in the extreme tail of the prior-driven structural null."
    )
    finalize_figure(
        fig,
        "supplement_figure_structural_null",
        output_dir,
        {"null_samples": null_samples, "null_summary": null_summary},
        alt_text,
        "Supplementary Figure: Structural Null",
        caption,
    )
    plt.close(fig)


def _write_readme(
    output_dir: Path,
    site_metrics: pd.DataFrame,
    regression_summary: pd.DataFrame,
    loo: pd.DataFrame,
    predictor_table: pd.DataFrame,
    null_summary: pd.DataFrame,
) -> None:
    rel = regression_summary.set_index("relationship")
    null_row = null_summary.iloc[0]
    loo_sign_change = bool((loo["slope"] <= 0).any())
    readme = f"""# Figure 10 posterior analysis

Generated on Sunday, July 19, 2026.

## Methods

- Site set: 34 sites matching the current Figure 10 universe: 24 direct-warming network sites plus 10 incubation-expansion sites.
- Posterior sources:
  - Saved MCMC chains were reused for `US-Ha1`, `US-A10`, `US-Ho1`, and `US-EML`.
  - Gaussian posterior draws were regenerated in parallel for the remaining sites from each site's OE posterior mean and covariance.
- Warming experiment: the existing standardized `+4 C`, `100-year` repeated-forcing experiment.
- Monte Carlo propagation: {_mcmc.MC_ITERATIONS:,} cross-site iterations, each drawing one posterior sample per site.
- Structural null: independent prior draws at each site propagated through the same warming experiment.

## Main results

- Turnover separation vs old-fraction:
  - slope median = {rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'slope_median']:.3f}
  - slope 95% = [{rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'slope_q025']:.3f}, {rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'slope_q975']:.3f}]
  - Pearson r median = {rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'pearson_r_median']:.3f}
  - Pearson r 95% = [{rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'pearson_r_q025']:.3f}, {rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'pearson_r_q975']:.3f}]
  - Spearman rho median = {rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'spearman_rho_median']:.3f}
  - Spearman rho 95% = [{rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'spearman_rho_q025']:.3f}, {rel.loc['old_fraction_of_excess_rh__vs__turnover_separation', 'spearman_rho_q975']:.3f}]

- Turnover separation vs fractional C loss:
  - Pearson r median = {rel.loc['frac_c_loss__vs__turnover_separation', 'pearson_r_median']:.3f}
  - Pearson r 95% = [{rel.loc['frac_c_loss__vs__turnover_separation', 'pearson_r_q025']:.3f}, {rel.loc['frac_c_loss__vs__turnover_separation', 'pearson_r_q975']:.3f}]
  - Spearman rho median = {rel.loc['frac_c_loss__vs__turnover_separation', 'spearman_rho_median']:.3f}
  - Spearman rho 95% = [{rel.loc['frac_c_loss__vs__turnover_separation', 'spearman_rho_q025']:.3f}, {rel.loc['frac_c_loss__vs__turnover_separation', 'spearman_rho_q975']:.3f}]

- Turnover separation vs total DFS:
  - Pearson r median = {rel.loc['dfs_total__vs__turnover_separation', 'pearson_r_median']:.3f}
  - Pearson r 95% = [{rel.loc['dfs_total__vs__turnover_separation', 'pearson_r_q025']:.3f}, {rel.loc['dfs_total__vs__turnover_separation', 'pearson_r_q975']:.3f}]

- Leave-one-site-out robustness:
  - slope range = [{loo['slope'].min():.3f}, {loo['slope'].max():.3f}]
  - Pearson r range = [{loo['pearson_r'].min():.3f}, {loo['pearson_r'].max():.3f}]
  - Spearman rho range = [{loo['spearman_rho'].min():.3f}, {loo['spearman_rho'].max():.3f}]
  - Any sign change in slope: {'yes' if loo_sign_change else 'no'}

- Structural null:
  - observed Pearson r = {null_row['observed_pearson_r']:.3f}
  - null median = {null_row['null_pearson_r_median']:.3f}
  - null 95% = [{null_row['null_pearson_r_q025']:.3f}, {null_row['null_pearson_r_q975']:.3f}]
  - observed percentile = {null_row['observed_percentile']:.1f}
  - empirical p = {null_row['empirical_p_two_sided']:.4f}

## Files

- `figures/figure_10.*`: revised Figure 10
- `figures/supplement_figure_structural_null.*`: structural-null figure
- `csv/figure_10/posterior_site_metrics.csv`: site summary table
- `csv/figure_10/posterior_regression_summary.csv`: posterior regression summary
- `csv/figure_10/leave_one_out.csv`: leave-one-site-out table
- `csv/figure_10/predictor_comparison.csv`: predictor comparison table
"""
    (output_dir / "README.md").write_text(readme, encoding="utf-8")
