import fs from "node:fs/promises";
import { FileBlob, PresentationFile } from "@oai/artifact-tool";

const root = "/Users/newtonnguyen/Documents/ecosystem-complexity";
const source = `${root}/notebooks/ecosystem_complexity_soil_carbon_canonical_presentation.pptx`;
const output = `${root}/notebooks/ecosystem_complexity_soil_carbon_canonical_presentation.pptx`;

async function bytes(path) {
  const b = await fs.readFile(path);
  return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength);
}
async function writeBlob(path, blob) {
  await fs.writeFile(path, new Uint8Array(await blob.arrayBuffer()));
}
function textbox(slide, text, position, style = {}) {
  const shape = slide.shapes.add({
    geometry: "textbox", position, fill: "none",
    line: { style: "solid", fill: "none", width: 0 },
  });
  shape.text = text;
  shape.text.style = { fontFace: "Calibri", color: "#2A2A2A", ...style };
  return shape;
}
function rect(slide, position, fill, line = fill) {
  return slide.shapes.add({ geometry: "rect", position, fill, line: { style: "solid", fill: line, width: 1 } });
}
function notes(slide, body) {
  if (slide.notes?.setText) slide.notes.setText(body);
}

const presentation = await PresentationFile.importPptx(await FileBlob.load(source));
const figure = await bytes(`${root}/notebooks/paper_figs/outputs/current_results/figures/figure_11_transit_times.png`);
const slide = presentation.slides.add();
slide.background.fill = "#FFFFFF";
textbox(slide, "CROSS-ECOSYSTEM RESULTS  ·  04", { left: 58, top: 30, width: 1080, height: 28 },
  { fontSize: 13, bold: true, color: "#4A7C59", charSpacing: 3 });
textbox(slide, "Transit time combines turnover and carbon routing", { left: 58, top: 62, width: 1120, height: 48 },
  { fontFace: "Georgia", fontSize: 27, bold: true, color: "#1F3A2E" });
textbox(slide, "28 / 28", { left: 1180, top: 682, width: 60, height: 20 },
  { fontSize: 9, color: "#6B6B6B", alignment: "right" });
slide.images.add({ blob: figure, contentType: "image/png", alt: "Input-weighted intrinsic transit times for 34 optimized ecosystems", fit: "contain", position: { left: 35, top: 145, width: 835, height: 495 } });
textbox(slide, "HOW TO READ THIS", { left: 900, top: 162, width: 290, height: 24 }, { fontSize: 11, bold: true, color: "#4A7C59", charSpacing: 2 });
textbox(slide, "Transit time is the expected time from soil entry to respiratory exit, weighted by where carbon enters the model.", { left: 900, top: 200, width: 292, height: 105 }, { fontFace: "Georgia", fontSize: 16, bold: true, color: "#1F3A2E" });
textbox(slide, "• Median: 12.2 years\n• Range: 6.0–39.1 years\n• EML is shortest; Trumbore Musick is longest\n• Squares are incubation-expansion sites.", { left: 900, top: 334, width: 292, height: 125 }, { fontSize: 13, color: "#2A2A2A" });
rect(slide, { left: 890, top: 505, width: 315, height: 105 }, "#F7F4ED", "#D4A574");
textbox(slide, "Reference-environment diagnostic: optimized MAP turnover times plus the configured transfer fractions. Environmental modifiers and unpersisted MAP transfer logits are not included.", { left: 910, top: 522, width: 275, height: 70 }, { fontSize: 11.5, italic: true, color: "#1F3A2E" });
notes(slide, "[Sources]\nTransit-time figure generated by apps/compute_transit_times.py from notebooks/exports/network_inversion_fluxcom_er_20260719/site_summary.csv.\n[/Sources]");

const pptx = await PresentationFile.exportPptx(presentation);
await pptx.save(output);
await writeBlob(`${root}/.tmp_figs_9_10_deck/slide-28.png`, await presentation.export({ slide, format: "png", scale: 1 }));
console.log(output);
